version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '107.191.43.195'"
    environment:
      REDIS_CACHE_HOST: 'redis-11326.c240.us-east-1-3.ec2.cloud.redislabs.com'
      REDIS_CACHE_PORT: 11326
      REDIS_CACHE_PASSWORD: 'J5Kn6pErUyhfUu3m1aggMOZW6uAeTzDg'
    volumes:
      - .:/stocket-api
    ports:
      - '3000:3000'
    depends_on:
      - db
