default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # username: postgres
  # password: password

development:
  <<: *default
  database: stocket_api_development

test:
  <<: *default
  database: stocket_api_test
  username: postgres
  password: password

staging:
  url: <%= ENV['DATABASE_STAGING_URL'] %>

production:
  <<: *default
  database: stocket_api_production
  username: postgres
  password: <%= ENV['STOCKET_API_DATABASE_PASSWORD'] %>
