default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: stocket_api_development
  url: postgresql://localhost:5434
test:
  <<: *default
  database: stocket_api_test
  username: postgres
  password: password
  url: postgresql://localhost:5434
production:
  <<: *default
  database: stocket_api_production
  username: postgres
  password: <%= ENV['STOCKET_API_DATABASE_PASSWORD'] %>
  url: postgresql://207.246.91.135:5433
