---
default:
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: '<%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>'
development:
  adapter: postgresql
  database: stocket_api_development
  encoding: unicode
  host: localhost
  pool: '<%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>'
production:
  adapter: postgresql
  database: stocket_api_production
  encoding: unicode
  host: 207.246.91.135
  port: 5433
  password: "<%= ENV['STOCKET_API_DATABASE_PASSWORD'] %>"
  pool: '<%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>'
  username: postgres
  url: postgresql://207.246.91.135:5433
staging:
  url: "<%= ENV['DATABASE_STAGING_URL'] %>"
test:
  adapter: postgresql
  database: stocket_api_test
  encoding: unicode
  host: localhost
  password: password
  pool: '<%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>'
  username: postgres
